##############
# 自定义配置 #
##############
app.debug = true
app.version = 0.01

############
# 指定端口 #
############
server.port = 7100
#################################
# 指定主数据源 可以有多个数据源 #
#################################
spring.datasource.driverClassName = com.mysql.jdbc.Driver
spring.datasource.url = jdbc:mysql://tank.usuusuit.com:3306/hazuki_dev?useUnicode=true&characterEncoding=UTF-8
#spring.datasource.url = jdbc:mysql://tank.usuusuit.com:3306/hazuki?useUnicode=true&characterEncoding=UTF-8
spring.datasource.username = hazuki
spring.datasource.password = Hazuki@456
###############################
# 日志文件配置 使用默认的配置 #
###############################
logging.file = /home/log/hazuki_spring.log
######################
# 关闭傻逼的权限控制 #
######################
security.basic.enabled=false
##################
# 指定格式化时区 #
##################
spring.jackson.time-zone = GMT+8
#############################
# 设置控制台打印执行sql情况 #
#############################
spring.jpa.show-sql = true
############
# 邮件配置 #
############
spring.mail.protocol=smtps
spring.mail.host=smtp.126.com
spring.mail.port=465
spring.mail.username=eyeblue@126.com
spring.mail.password=eyeblue_password
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtps.auth=true
spring.mail.properties.mail.smtps.starttls.enable=true
spring.mail.properties.mail.smtps.debug=true